name: customer-support
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.8
  - numpy=1.24.0
  - pandas
  - scikit-learn
  - pip
  - pip:
    - dill
    - mlflow
    - matplotlib
    - seaborn